name: "SMS Gateway"
version: "1.1.5"
stage: stable
slug: "sms_gateway"
description: "SMS Gateway for MQTT using a usb GSM dongle"
codenotary: "helios14_75@hotmail.fr"
url: "https://github.com/Helios06/sms_gateway"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
hassio_role: default
hassio_api: false
auth_api: false
ingress: false
init: false
options:
  GSM_Mode: "Enter 'modem' or 'api'"
  GSM_Device: "/dev/ttyUSB1"
  GSM_PIN: "0000"
  GSM_AUTH: "+336XXXXXXXX"
  MQTT_Host: "homeassistant.local"
  MQTT_Port: "1883"
  MQTT_User: "mqtt"
  MQTT_Password: "mqtt"
  MQTT_Receive: "sms_received"
  MQTT_Send: "send_sms"
  ADDON_Logging: "INFO"
schema:
  GSM_Mode: str
  GSM_Device: str
  GSM_PIN: str
  GSM_AUTH: str
  MQTT_Host: str
  MQTT_Port: str
  MQTT_User: str
  MQTT_Password: str
  MQTT_Receive: str
  MQTT_Send: str
  ADDON_Logging: str
devices: [/dev/ttyUSB0,/dev/ttyUSB1]
