name: "SMS Gateway"
description: "SMS Gateway for MQTT using a usb GSM dongle"
version: "1.1.0"
url: https://github.com/Helios06/sms_gateway
slug: "sms_gateway"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  GSM_Mode: "Choose here 'modem' or 'api'"
  GSM_Device: "/dev/ttyUSB1"
  GSM_PIN: "0000"
  GSM_AUTH: "+336XXXXXXXX"
  MQTT_Host: "homeassistant.local"
  MQTT_Port: 1883
  MQTT_User: "mqtt"
  MQTT_Password: "mqtt"
  MQTT_Receive: "sms_received"
  MQTT_Send: "send_sms"
  ADDON_Logging: "INFO"
schema:
  GSM_Mode: str
  GSM_Device: str
  GSM_PIN: str
  GSM_AUTH: str
  MQTT_Host: str
  MQTT_Port: int
  MQTT_User: str
  MQTT_Password: str
  MQTT_Receive: str
  MQTT_Send: str
  ADDON_Logging: str
startup: services
devices: [/dev/ttyUSB0,/dev/ttyUSB1]
